@startuml クラス_欠席回数登録

skinparam classAttributeIconSize 0

' クラスの定義
class 出席状況 {
    - 欠席率
    - 出席回数
    - 累計欠席回数
}

class 学生情報 {
    - 氏名
    - 性別
    - 学生番号
    - 入学年度
    - コース
    - 学年
    - クラス
}

class 学生 {
    - 学生情報
    - 出席状況
    - 成績
    - 在学状況
}

' クラス間の関係

@enduml