@startuml
'クラス図の見た目の設定
skinparam classAttributeIconSize 0

'クラス図の定義
'シーケンス図のエンティティから持ってくる
'フィールドはドメインモデルからひし形の矢印のモノを持ってくる
Class "買い物内容"{
    - 合計金額:int
    + getter()
    + setter()
    + 参照する(int id):買い物内容
    + 更新する(object 買い物内容):boolean
    + 商品を入れる(object 品物):void
    + 商品を出す(object 品物):void
}

Class "ユーザー情報"{
    - ID:int:PK
    - Pass:String
    - 送付先住所:String
    - お気に入り品物:FK
    + getter()
    + setter()
    + ログインする(int id, String Pass):boolean
    + 購入者情報を取得する(int id):ユーザー情報
}

class "会員ユーザー"{
    - ユーザー情報:FK
    + getter()
    + setter()
}

' Class "お気に入り" {
'     -ユーザー情報:FK
'     -品物:FK
' }

Class "買い物履歴"{
    - ユーザー情報:FK
    - 日時:datetime
    - 買い物内容:FK
    + getter()
    + setter()
    + 登録する(object 買い物内容):boolean
}

Class "品物" {
    -品名:String
    -値段:int
    -品名コード:String:PK
    -産地・メーカー:String
    + getter()
    + setter()
}

Class "買い物客" {
    -買い物内容:FK
    -支払方法:String
    + getter()
    + setter()
}

Class "買い物詳細"{
    -買い物内容:FK
    -品物:FK
    -数量:int
    -小計:int
    + getter()
    + setter()
}

'クラス図の関連の定義
'マイナス一個だと横に、二個だと下につながる
'左に書くと上に配置される
'左に書くと左に配置される
'ユーザー情報からみて買い物履歴は複数存在する
'まだ購入したことがないユーザーの場合、下限は0

会員ユーザー "1" -- "1" ユーザー情報
買い物詳細 "0..*" - "1" 品物
買い物内容 "1" -- "0..*" 買い物詳細
買い物客 "1" -- "1" 買い物内容
買い物履歴 "0..*" - "1" ユーザー情報
買い物内容 "0..1" - "0..1" 買い物履歴
ユーザー情報 "0..*" -- "0..*" 品物


' '継承関係
会員ユーザー --|> 買い物客

@enduml