@startuml クラス_欠席回数登録

skinparam classAttributeIconSize 0

' クラスの定義
class 出席状況 {
    - 欠席率
    - 出席回数
    - 累計欠席回数
}

class 学生情報 {
    - 氏名
    - 性別
    - 学生番号
    - 在学状況
    - 入学年度
    - コース
}

' クラス間の関係
学生情報 "1" - "  0..*" 出席状況

@enduml