@startuml 学生情報登録

actor    "教職員"          as User
boundary "学生情報閲覧画面" as b1
control  "表示"            as c1
boundary "学生情報登録画面" as b2
'入力内容を確認する
control  "処理"            as c2
'DBへの操作
control  "処理"            as c3
entity   "学生情報"        as e1
boundary "完了画面"        as b3


'流れ
c1    -> e1:参照する():method=GET()
c1   <-- e1
c1    -> b1:表示する():method=POST()
User  -> b1:「登録」ボタンを押下する
b1    -> b2:学生情報登録画面を表示する():method=POST()
User  -> b2:必要情報を入力し\n「登録完了」ボタンを押下する
b2    -> c2:入力内容を確認する

alt 未入力の項目があった場合
    c2  -> b2:「未入力の項目があります」とメッセージを表示する():method=POST()
else 未入力の項目がなかった場合
    c2  -> c3:起動する():POST()
    c3  -> e1:登録する():boolean
    c3 <-- e1
    c3  -> b3:完了画面を表示():method=POST()
end

@enduml