@startuml シーケンス_科目登録

actor    "教職員"              as User
boundary "科目管理画面"         as b1
control  "表示"                as c1
boundary "科目情報登録画面"     as b2
boundary "科目情報登録完了画面" as b3
control  "処理"                as c2
control  "処理"                as c3
entity   "科目"                as e1

'シーケンスの流れ
c1   -> e1:参照する()
e1  --> c1
c1   -> b1:表示する()method=POST()
User -> b1:「新規登録」ボタンを押下する
b1   -> b2:科目情報登録画面を表示する()

alt 「登録」ボタンを押下した場合
  User -> b2:「登録」ボタンを押下する
  b2   -> c2:起動するmethod=POST()
  
  alt 「科目コード」が無記入の場合
    c2 -> b2:「科目コードが入力されていません」\nとメッセージを表示する()
  
  else 「科目名」が無記入の場合
    c2 -> b2:「科目名が入力されていません」\nとメッセージを表示する()
  
  else 「科目コード」「科目名」が無記入でない場合
    c2  -> e1:参照する()
    e1 --> c2

    alt すでに「科目コード」が存在する場合
      c2 -> b2:「科目コードが重複しています。\nと画面に表示する()

    else 「科目コード」が存在しない場合
      b3  -> c3:起動する:method=POST()
      c3  -> e1:登録する():boolean()
      c3 <-- e1
      c3  -> b3:科目情報登録完了画面を表示する():method=POST()
      
    end

  end

else 「戻る」ボタンを押下した場合
  b2 -> b1:科目管理画面を表示する()

end
@enduml